spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    pool:
      initial-size: 10
      max-size: 20
app:
  jwt:
    secret: 804fc575-3fe3-4c8f-b985-69716d940831
springdoc:
  show-login-endpoint: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
